### ISSUE TITLE
Add ability to ignore other branches

### ISSUE THREAD

**Issue by grhm** [sierpinski/BlitzBranches#4]
We use a git-flow type setup, which advocates having a "master" and a "develop" branch.  This means people using git-flow will want look not just ignore branches called "master".

To make matters worse, we've got non-standard branch names.  "Released" instead of "master" and "Tested" instead of "develop".

It would be nice to be able to configure which branches to ignore.

(I have forked and made a local change that works for me  - but i don't know how to make it configurable to be useful to others)

**Comment by sierpinski** [comment]
This is definitely something we could do. I'll take a look.

**Comment by sierpinski** [comment]
Added this in version 0.5.8. It is under "Options". Then, you can select a branch or branches to ignore. Thanks for the request! Let me know what you think.
