### ISSUE TITLE
Feature Request: Exclude well defined branches

### ISSUE THREAD

**Issue by NelsonLamprecht** [sierpinski/BlitzBranches#5]
Our team just installed the BlitzBranches, what would be helpful would be to allow us to define, in addition to the "master" branch, branches that we generally acknowledge as excluding from the results e.g:
rc
features
etc..

**Comment by sierpinski** [comment]
There was a similar branch from another user. Let me see what I can do.

**Comment by sierpinski** [comment]
Added this in version 0.5.8. Click "Options" and then you can select a branch or branches to ignore. Let me know what you think.

**Comment by NelsonLamprecht** [comment]
I think this a good start!.
How can we persist these options so it always hides branches called "features" etc.
We saw in the code how you ignore master, just curious if there is a way to make that configurable so others can use that in a persistent fashion?

**Comment by sierpinski** [comment]
Hi Nelson, this is possible. I would need to save your “exclusion” branch choices. I dont know when i can get to it. It might help to make a new issue specific to this request.
