### ISSUE TITLE
From Comment: Make columns of table sortable, filterable.

### ISSUE THREAD

**Issue by sierpinski** [sierpinski/BlitzBranches#6]
User requests to be able to sort and filter on the columns of the table.

**Comment by gcsizmadia** [comment]
Hi @sierpinski , 
I'm just wondering if there is any progress in this enhancement.

**Comment by sierpinski** [comment]
Hi @gcsizmadia I am not actively supporting these extensions, so I don't have a plan to implement new features. Would this be beneficial to you?

**Comment by gcsizmadia** [comment]
@sierpinski, sorry to hear that but I understand. But yes, it would be great benefit as we have an increasing number of branches (and repositories) as well.

**Comment by sierpinski** [comment]
I pushed up a quick change that adds searching the table for text and simple sorting on the columns. Hope it helps.
