### ISSUE TITLE
Feature Request: Enhanced Branch filtering

### ISSUE THREAD

**Issue by Sebbl22** [sierpinski/BlitzBranches#7]
We use this extension on a large number of repositories and branches in a single TFS collection (218 non-Master branches). Each repository is using the GitFlow branching strategy, so we have master, develop, hotfix/*, release/* and feature/* branches.

My intention is to find "stale" branches like old feature or release-branches. It would be great to enhance the current filtering options, so that we can skip not only master-branches, but also develop-branches. It is possible with the current filtering panel, but we have to find and select every develop-branch manually, which takes a long time.
Maybe a regex-like filter would be possible?

**Comment by sierpinski** [comment]
Updated to allow excluding branches which contain text in comma separated list. Should enable your scenario. Not perfect, but hopefully if you still use this extension helps you.
