### ISSUE TITLE
Can we have an icon for the new VSTS side menus

### ISSUE THREAD

**Issue by MikeWilliams-UK** [sierpinski/BlitzBranches#8]
![image](https://user-images.githubusercontent.com/13162784/49504666-0d6ce280-f872-11e8-9b78-49a1e5c65568.png)

**Comment by sierpinski** [comment]
Hi! I just added this! Hope you like it! Here's an example of how it looks!

![image](https://user-images.githubusercontent.com/9721083/78976776-bf05ce80-7acb-11ea-92f2-0171336012fe.png)
